version: "3.9"

services:
  db:
    image: 'postgres:10.6-alpine'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cards
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbadmin
    ports:
      - 5432:5432
  web:
    build: .
    command: python ./manage.py runserver 0.0.0.0:8000
    volumes:
      - /cardsRestApi
    ports:
      - 8000:8000